[package]
name = "game-of-life"
version = "1.2.3"
publish = false
authors = ["Max Machon <max@machon.family>"]
edition = "2021"
readme = "README.md"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
drawille = "*"
rand = "*"
