---
name: Release

on: [push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install release dependencies
        run: npm ci

      - name: Lint
        run: cargo clippy

      - name: Check
        run: cargo check

      - name: Test
        run: cargo test

      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
