---
name: Release

on: [push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Setup rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Lint
        run: cargo clippy

      - name: Check
        run: cargo check

      - name: Test
        run: cargo test

      - name: Add semantic-release plugins
        run: |
          npm install -g @semantic-release/git
          npm install -g @semantic-release/changelog
          npm install -g @semantic-release/exec

      - name: Release
        run: npx semantic-release
